### ISSUE TITLE
DOcplexLimitsExceeded

### ISSUE THREAD

**Issue by phtay2011** [IBMDecisionOptimization/docplex-examples#25]
Hi,

I'm getting this error
`DOcplexLimitsExceeded: **** Promotional version. Problem size limits exceeded, CPLEX code=1016`

This is the full logs

`CPLEX Error  1016: Community Edition. Problem size limits exceeded. Purchase at http://ibm.biz/error1016.
Traceback (most recent call last):

  File "C:\Users\User\Anaconda3\envs\cs601env\lib\site-packages\docplex\mp\cplex_engine.py", line 2031, in solve
    cpx.solve()

  File "C:\Users\User\Anaconda3\envs\cs601env\lib\site-packages\cplex\__init__.py", line 1329, in solve
    _proc.mipopt(self._env._e, self._lp)

  File "C:\Users\User\Anaconda3\envs\cs601env\lib\site-packages\cplex\_internal\_procedural.py", line 692, in mipopt
    check_status(env, status)

  File "C:\Users\User\Anaconda3\envs\cs601env\lib\site-packages\cplex\_internal\_procedural.py", line 236, in __call__
    raise CplexSolverError(error_string, env, status)

CplexSolverError: CPLEX Error  1016: Community Edition. Problem size limits exceeded. Purchase at http://ibm.biz/error1016.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-7-fc9f0b1872e9>", line 1, in <module>
    base_sol = model_base.solve(log_output=True)

  File "C:\Users\User\Anaconda3\envs\cs601env\lib\site-packages\docplex\mp\model.py", line 4216, in solve
    return self._solve_local(context, force_clean_before_solve, lex_timelimits, lex_mipgaps)

  File "C:\Users\User\Anaconda3\envs\cs601env\lib\site-packages\docplex\mp\model.py", line 4356, in _solve_local
    raise docpx_e

  File "C:\Users\User\Anaconda3\envs\cs601env\lib\site-packages\docplex\mp\model.py", line 4343, in _solve_local
    lex_mipgaps=lex_mipgaps)

  File "C:\Users\User\Anaconda3\envs\cs601env\lib\site-packages\docplex\mp\cplex_engine.py", line 2062, in solve
    self._model.fatal_ce_limits()

  File "C:\Users\User\Anaconda3\envs\cs601env\lib\site-packages\docplex\mp\model.py", line 904, in fatal_ce_limits
    self._error_handler.fatal_limits_exceeded()

  File "C:\Users\User\Anaconda3\envs\cs601env\lib\site-packages\docplex\mp\error_handler.py", line 214, in fatal_limits_exceeded
    raise DOcplexLimitsExceeded()

DOcplexLimitsExceeded: **** Promotional version. Problem size limits exceeded, CPLEX code=1016`

**Comment by vlkong** [comment]
Hi,

when you `pip install cplex`, this installs the CPLEX Community edition that is limited to 1000 constraints or variables.

You need CPLEX full edition to handle your model.
If you are a student, teacher or researcher, you are entitled for the [academic version](https://www.ibm.com/academic/technology/data-science).

Best regards,
